"""Reeloom run state, events, policies, and event storage."""

from reeloom.runtime.events import (
    ApplyFailed,
    ApplyStarted,
    ArchiveDirectoryListed,
    ArchiveSearchObserved,
    ApprovalRequested,
    CandidateSnapshotCreated,
    ExistingInventoryObserved,
    MappingRejected,
    MappingReviewCaptured,
    MappingSubmitted,
    ModelUsageRecorded,
    MoveApplied,
    PlanApproved,
    PlanBuilt,
    RollbackCompleted,
    RunCompleted,
    RunFailed,
    RunStarted,
    RunStopped,
    RuntimeEvent,
    SeriesSelected,
    SubtitleVariantDetected,
    TmdbCandidatesObserved,
    TmdbSeasonCatalogObserved,
    ToolRejected,
    ToolRequested,
    ToolSucceeded,
)
from reeloom.runtime.reducer import reduce_event
from reeloom.runtime.resume import ApprovalResumeService
from reeloom.runtime.state import (
    MappingValidationIssue,
    Phase,
    RunState,
    RunStatus,
    StopReason,
)
from reeloom.runtime.store import EventStore, InMemoryEventStore, StoredEvent

__all__ = [
    "InMemoryEventStore",
    "EventStore",
    "ApplyFailed",
    "ApplyStarted",
    "ArchiveDirectoryListed",
    "ArchiveSearchObserved",
    "ApprovalRequested",
    "ApprovalResumeService",
    "CandidateSnapshotCreated",
    "ExistingInventoryObserved",
    "MappingRejected",
    "MappingReviewCaptured",
    "MappingSubmitted",
    "MappingValidationIssue",
    "ModelUsageRecorded",
    "Phase",
    "MoveApplied",
    "PlanApproved",
    "PlanBuilt",
    "RollbackCompleted",
    "RunCompleted",
    "RunFailed",
    "RunStarted",
    "RunState",
    "RunStatus",
    "RunStopped",
    "RuntimeEvent",
    "StopReason",
    "StoredEvent",
    "SeriesSelected",
    "SubtitleVariantDetected",
    "TmdbCandidatesObserved",
    "TmdbSeasonCatalogObserved",
    "ToolRejected",
    "ToolRequested",
    "ToolSucceeded",
    "reduce_event",
]
