"""Reeloom run state, events, policies, and event storage."""

from reeloom.runtime.events import (
    ApprovalRequested,
    CandidateSnapshotCreated,
    ExistingInventoryObserved,
    MappingRejected,
    MappingSubmitted,
    ModelUsageRecorded,
    PlanBuilt,
    RunFailed,
    RunStarted,
    RunStopped,
    RuntimeEvent,
    SeriesSelected,
    SubtitleVariantDetected,
    TmdbCandidatesObserved,
    TmdbSeasonCatalogObserved,
    ToolRejected,
    ToolRequested,
    ToolSucceeded,
)
from reeloom.runtime.reducer import reduce_event
from reeloom.runtime.state import (
    MappingValidationIssue,
    Phase,
    RunState,
    RunStatus,
    StopReason,
)
from reeloom.runtime.store import InMemoryEventStore, StoredEvent

__all__ = [
    "InMemoryEventStore",
    "ApprovalRequested",
    "CandidateSnapshotCreated",
    "ExistingInventoryObserved",
    "MappingRejected",
    "MappingSubmitted",
    "MappingValidationIssue",
    "ModelUsageRecorded",
    "Phase",
    "PlanBuilt",
    "RunFailed",
    "RunStarted",
    "RunState",
    "RunStatus",
    "RunStopped",
    "RuntimeEvent",
    "StopReason",
    "StoredEvent",
    "SeriesSelected",
    "SubtitleVariantDetected",
    "TmdbCandidatesObserved",
    "TmdbSeasonCatalogObserved",
    "ToolRejected",
    "ToolRequested",
    "ToolSucceeded",
    "reduce_event",
]
